{% set name = "borneo" %}
{% set version = "5.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/borneo-{{ version }}.tar.gz
  sha256: e1205db61d29fb2c7bbfb71de7021d7d933048c950314c97aa39c058efadfb7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil >=2.7.0
    - requests >=2.12.0

test:
  imports:
    - borneo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://nosql-python-sdk.readthedocs.io/en/stable/index.html
  summary: Oracle NoSQL Database Python SDK
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - beckermr
